### ISSUE TITLE
对象权限问题，如何解决？

### ISSUE THREAD

**Issue by flyingdown** [hequan2017/go-admin#1]
readme中的例子，可以控制test访问user表，但表里的所有数据都可以访问，如何控制用户只能访问自己的用户数据，比如test用户只能访问自己创建的用户数据？

**Comment by hequan2017** [comment]
可以再写一个中间件，负责检查更 细一步的 判断条件。 或者去看下 casbin 是否支持。

**Comment by hequan2017** [comment]
你可以看下 https://casbin.org/docs/zh-CN/abac  ，  把rbac改成 abac
