### ISSUE TITLE
"msg": "Token错误"

### ISSUE THREAD

**Issue by wms3001** [hequan2017/go-admin#10]
curl -X POST "http://127.0.0.1:8000/auth" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"password\": \"admin\", \"username\": \"123456\"}"

{
  "code": 401,
  "data": null,
  "msg": "Token错误"
}

**Comment by hequan2017** [comment]
"{ "password": "admin", "username": "123456"}"   写反了
