### ISSUE TITLE
作者你好，我是新手，我跑你的项目直接报错，希望能帮我看看。

### ISSUE THREAD

**Issue by vastyang** [hequan2017/go-admin#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x117c4e2]

goroutine 1 [running]:
github.com/casbin/casbin/model.Model.RemoveFilteredPolicy(0xc0003d2120, 0x178722c, 0x1, 0x178722c, 0x1, 0x1, 0xc0004b33c0, 0x1, 0x1, 0xc0003b4180)
        /Users/Yang/Desktop/Go/src/github.com/casbin/casbin/model/policy.go:115 +0xc2
github.com/casbin/casbin.(*Enforcer).removeFilteredPolicy(0xc00010e310, 0x178722c, 0x1, 0x178722c, 0x1, 0x1, 0xc0004b33c0, 0x1, 0x1, 0x2f35d80)
        /Users/Yang/Desktop/Go/src/github.com/casbin/casbin/internal_api.go:67 +0x9e
github.com/casbin/casbin.(*Enforcer).RemoveFilteredNamedGroupingPolicy(0xc00010e310, 0x178722c, 0x1, 0x1, 0xc0004b33c0, 0x1, 0x1, 0xc0004b33c0)
        /Users/Yang/Desktop/Go/src/github.com/casbin/casbin/management_api.go:254 +0x8c
github.com/casbin/casbin.(*Enforcer).RemoveFilteredGroupingPolicy(0xc00010e310, 0x1, 0xc0004b33c0, 0x1, 0x1, 0xc00012e730)
        /Users/Yang/Desktop/Go/src/github.com/casbin/casbin/management_api.go:229 +0x68
github.com/casbin/casbin.(*Enforcer).DeleteRole(0xc00010e310, 0xc0004b0570, 0x4)
        /Users/Yang/Desktop/Go/src/github.com/casbin/casbin/rbac_api.go:70 +0x82
github.com/hequan2017/go-admin/service/role_service.(*Role).LoadPolicy(0xc0001582a0, 0x1, 0x1, 0x0)
        /Users/Yang/Desktop/Go/src/github.com/hequan2017/go-admin/service/role_service/role.go:143 +0x87
github.com/hequan2017/go-admin/service/role_service.(*Role).LoadAllPolicy(0xc0001582a0, 0x8, 0xc0003d21b0)
        /Users/Yang/Desktop/Go/src/github.com/hequan2017/go-admin/service/role_service/role.go:128 +0x83
github.com/hequan2017/go-admin/middleware/inject.LoadCasbinPolicyData(0x0, 0x1858c60)
        /Users/Yang/Desktop/Go/src/github.com/hequan2017/go-admin/middleware/inject/inject.go:61 +0x3d
main.main()
        /Users/Yang/Desktop/Go/src/github.com/hequan2017/go-admin/main.go:33 +0x48
exit status 2

**Comment by vastyang** [comment]
mac用户注意一下：
if osType == "windows" {
		path = "conf\\rbac_model.conf"
	} else if osType == "linux" {
		path = "conf/rbac_model.conf"
}
path不对的问题。

**Comment by hequan2017** [comment]
问题收到

**Comment by vastyang** [comment]
@hequan2017 作者能加我微信吗695353366，探讨探讨。
