### ISSUE TITLE
Potential case-insensitive import collision

### ISSUE THREAD

**Issue by unknwon** [hequan2017/go-admin#4]
Due to GitHub handle change (to lowercase) for long term purpose, `go get` may fail fetching `github.com/Unknwon/com`. 
Please consider take some time to update it to `github.com/unknwon/com` in the `go.mod` file.
I truly apology for the inconvenience and unintended troubles caused.

**Comment by hequan2017** [comment]
ok

**Comment by songoow** [comment]
go mod 里面加了 com 是不是会报错啊  
我这边显示为 go mod unexpect moudle path “github.com/unknown/com”
