### ISSUE TITLE
go mod 添加 unknown/com 报错

### ISSUE THREAD

**Issue by songoow** [hequan2017/go-admin#5]
go mod 里面加了 com 是不是会报错啊
我这边显示为 go mod unexpect moudle path “github.com/unknwon/com”

**Comment by songoow** [comment]
是不是因为unknwon/com 包的版本位V0 的格式，不是正确的V1.2.3的原因啊

**Comment by songoow** [comment]
go: finding github.com/Unknwon/com latest
go: github.com/Unknwon/com@v0.0.0-20190804042917-757f69c95f3e: parsing go.mod: unexpected module path "github.com/unknwon/com"
go: error loading module requirements

**Comment by hequan2017** [comment]
我检查一下

**Comment by hequan2017** [comment]
最新版 修复了。 是因为 之前是大写的地址，后面换成小写的，没有进行及时替换造成的。

**Comment by songoow** [comment]
谢谢
