### ISSUE TITLE
swag init出错

### ISSUE THREAD

**Issue by zinwalin** [hequan2017/go-admin#9]
```
mba➜  go-admin git:(master) ✗  >swag init
2019/10/21 16:42:50 Generate swagger docs....
2019/10/21 16:42:50 Generate general API Info, search dir:./
2019/10/21 16:42:50 ParseComment error in file routers/api/v1/role.go :can not find schema type: "v1.json"
```

**Comment by hequan2017** [comment]
我看看

**Comment by hequan2017** [comment]
E:\go-admin>swag init
2019/10/21 14:02:12 Generate swagger docs....
2019/10/21 14:02:12 Generate general API Info
2019/10/21 14:02:12 Generating models.Menu
2019/10/21 14:02:12 Generating models.Role
2019/10/21 14:02:12 Generating models.AuthSwag
2019/10/21 14:02:12 Skipping 'models.Role', already present.
2019/10/21 14:02:12 Generating models.User
2019/10/21 14:02:12 Skipping 'models.Menu', already present.
2019/10/21 14:02:12 create docs.go at  docs/docs.go

我测试没问题呀。

**Comment by zinwalin** [comment]
> E:\go-admin>swag init
> 2019/10/21 14:02:12 Generate swagger docs....
> 2019/10/21 14:02:12 Generate general API Info
> 2019/10/21 14:02:12 Generating models.Menu
> 2019/10/21 14:02:12 Generating models.Role
> 2019/10/21 14:02:12 Generating models.AuthSwag
> 2019/10/21 14:02:12 Skipping 'models.Role', already present.
> 2019/10/21 14:02:12 Generating models.User
> 2019/10/21 14:02:12 Skipping 'models.Menu', already present.
> 2019/10/21 14:02:12 create docs.go at docs/docs.go
> 
> 我测试没问题呀。

是不是跟swag版本有关？  代码没改动过。

**Comment by hequan2017** [comment]
你可以对比一下  swag版本。或者再看看相关资料

**Comment by zinwalin** [comment]
> 你可以对比一下 swag版本。或者再看看相关资料

你用的swag版本是多少？ 我用的是1.6.3

**Comment by zinwalin** [comment]
我用这修法解决了， 把json改成string
```
// @Success 200 {string} json "{ "code": 200, "data": {}, "msg": "ok" }"
// @Failure 400 {string} json
```
```

// @Success 200 {string} string "{ "code": 200, "data": {}, "msg": "ok" }"
// @Failure 400 {string} string
```
